#!/bin/bash

rm -f ${GITHUB_WORKSPACE}/files/geoip.db ${GITHUB_WORKSPACE}/files/geosite.db

actions_date=$(date)
geoip_last_ver=$(curl -Ls "https://api.github.com/repos/SagerNet/sing-geoip/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
geosite_last_ver=$(curl -Ls "https://api.github.com/repos/SagerNet/sing-geosite/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')

wget -N https://github.com/SagerNet/sing-geoip/releases/download/$geoip_last_ver/geoip.db -O ${GITHUB_WORKSPACE}/files/geoip.db
wget -N https://github.com/SagerNet/sing-geosite/releases/download/$geosite_last_ver/geosite.db -O ${GITHUB_WORKSPACE}/files/geosite.db

cat <<EOF > ${GITHUB_WORKSPACE}/files/singgeo-fetchlog.txt
# Sing-box Geoip and Geosite fetch log generated by GitHub Actions
Sing-geoip Last Version: $geoip_last_ver
Sing-geosite Last Version: $geosite_last_ver
Fetch Date: $actions_date
EOF

rm -f singgeoip.sh