name: Fetch Sing-box Geoip and Geosite latest version

on:
  workflow_dispatch:
  schedule:
    - cron: "30 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checking and fetching Sing-box latest version
        run: |
          wget -N https://raw.githubusercontent.com/taffychan/sing-box/main/.github/singgeoip.sh
          bash singgeoip.sh
      - name: Git uploading
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Uploaded by Github Actions, Date: $(date)"
          git push
      - name: Refreshing Jsdelivr
        run: |
          curl https://purge.jsdelivr.net/gh/taffychan/sing-box/files/geoip.db
          curl https://purge.jsdelivr.net/gh/taffychan/sing-box/files/geosite.db